// Section 4: El Arquitecto (Variables, Clones y Funciones)
// 60 lessons

import { MicroLesson, LessonType } from './microLessonSystem';
import { pLesson } from './programmingLessons';

export const SECTION_4_LESSONS: MicroLesson[] = [
    // Fase 1: Variables (1-15)
    pLesson('s4', 1, 'lesson', 'Lessons.programming.s4.l1.title', 'Lessons.programming.s4.l1.description', 'Lessons.programming.s4.l1.challenge', 'Lessons.programming.s4.l1.hint', ['crear_variable'], 3, 2, 10, 1),
    pLesson('s4', 2, 'lesson', 'Lessons.programming.s4.l2.title', 'Lessons.programming.s4.l2.description', 'Lessons.programming.s4.l2.challenge', 'Lessons.programming.s4.l2.hint', ['cambiar_variable', 'si', 'tocando_objeto'], 4, 3, 15, 1),
    pLesson('s4', 3, 'lesson', 'Lessons.programming.s4.l3.title', 'Lessons.programming.s4.l3.description', 'Lessons.programming.s4.l3.challenge', 'Lessons.programming.s4.l3.hint', ['cambiar_variable', 'si', 'tocando_objeto'], 4, 3, 15, 1),
    pLesson('s4', 4, 'lesson', 'Lessons.programming.s4.l4.title', 'Lessons.programming.s4.l4.description', 'Lessons.programming.s4.l4.challenge', 'Lessons.programming.s4.l4.hint', ['fijar_variable', 'bandera_verde'], 3, 2, 10, 1),
    pLesson('s4', 5, 'lesson', 'Lessons.programming.s4.l5.title', 'Lessons.programming.s4.l5.description', 'Lessons.programming.s4.l5.challenge', 'Lessons.programming.s4.l5.hint', ['mostrar_variable', 'esconder_variable'], 3, 2, 10, 1),
    pLesson('s4', 6, 'practice', 'Lessons.programming.s4.l6.title', 'Lessons.programming.s4.l6.description', 'Lessons.programming.s4.l6.challenge', 'Lessons.programming.s4.l6.hint', ['crear_variable', 'fijar_variable', 'cambiar_variable', 'si', 'tocando_objeto'], 5, 4, 20, 2),
    pLesson('s4', 7, 'practice', 'Lessons.programming.s4.l7.title', 'Lessons.programming.s4.l7.description', 'Lessons.programming.s4.l7.challenge', 'Lessons.programming.s4.l7.hint', ['si', 'operador_igual', 'decir', 'detener_todo', 'por_siempre'], 5, 4, 20, 2),
    pLesson('s4', 8, 'practice', 'Lessons.programming.s4.l8.title', 'Lessons.programming.s4.l8.description', 'Lessons.programming.s4.l8.challenge', 'Lessons.programming.s4.l8.hint', ['crear_variable', 'fijar_variable', 'cambiar_variable', 'esperar', 'por_siempre'], 5, 4, 20, 2),
    pLesson('s4', 9, 'practice', 'Lessons.programming.s4.l9.title', 'Lessons.programming.s4.l9.description', 'Lessons.programming.s4.l9.challenge', 'Lessons.programming.s4.l9.hint', ['fijar_variable', 'cambiar_variable', 'repetir', 'esperar', 'si', 'decir'], 5, 4, 20, 2),
    pLesson('s4', 10, 'practice', 'Lessons.programming.s4.l10.title', 'Lessons.programming.s4.l10.description', 'Lessons.programming.s4.l10.challenge', 'Lessons.programming.s4.l10.hint', ['crear_variable', 'mover_derecha', 'por_siempre'], 5, 4, 20, 2),
    pLesson('s4', 11, 'practice', 'Lessons.programming.s4.l11.title', 'Lessons.programming.s4.l11.description', 'Lessons.programming.s4.l11.challenge', 'Lessons.programming.s4.l11.hint', ['si', 'operador_mayor', 'cambiar_variable', 'tecla_presionada'], 6, 5, 25, 2),
    pLesson('s4', 12, 'practice', 'Lessons.programming.s4.l12.title', 'Lessons.programming.s4.l12.description', 'Lessons.programming.s4.l12.challenge', 'Lessons.programming.s4.l12.hint', ['al_hacer_click', 'cambiar_variable'], 4, 3, 15, 2),
    pLesson('s4', 13, 'practice', 'Lessons.programming.s4.l13.title', 'Lessons.programming.s4.l13.description', 'Lessons.programming.s4.l13.challenge', 'Lessons.programming.s4.l13.hint', ['al_hacer_click', 'cambiar_variable', 'si', 'operador_mayor'], 6, 5, 25, 2),
    pLesson('s4', 14, 'practice', 'Lessons.programming.s4.l14.title', 'Lessons.programming.s4.l14.description', 'Lessons.programming.s4.l14.challenge', 'Lessons.programming.s4.l14.hint', ['por_siempre', 'esperar', 'cambiar_variable'], 5, 4, 20, 2),
    pLesson('s4', 15, 'challenge', 'Lessons.programming.s4.l15.title', 'Lessons.programming.s4.l15.description', 'Lessons.programming.s4.l15.challenge', 'Lessons.programming.s4.l15.hint', ['al_hacer_click', 'cambiar_variable', 'si', 'operador_mayor', 'por_siempre', 'esperar', 'fijar_variable'], 8, 6, 40, 3),

    // Fase 2: Clones (16-30)
    pLesson('s4', 16, 'lesson', 'Lessons.programming.s4.l16.title', 'Lessons.programming.s4.l16.description', 'Lessons.programming.s4.l16.challenge', 'Lessons.programming.s4.l16.hint', ['crear_clon'], 4, 3, 15, 1),
    pLesson('s4', 17, 'lesson', 'Lessons.programming.s4.l17.title', 'Lessons.programming.s4.l17.description', 'Lessons.programming.s4.l17.challenge', 'Lessons.programming.s4.l17.hint', ['al_comenzar_como_clon', 'mover_derecha'], 4, 3, 15, 1),
    pLesson('s4', 18, 'practice', 'Lessons.programming.s4.l18.title', 'Lessons.programming.s4.l18.description', 'Lessons.programming.s4.l18.challenge', 'Lessons.programming.s4.l18.hint', ['por_siempre', 'crear_clon', 'al_comenzar_como_clon', 'mover_abajo'], 5, 4, 20, 2),
    pLesson('s4', 19, 'lesson', 'Lessons.programming.s4.l19.title', 'Lessons.programming.s4.l19.description', 'Lessons.programming.s4.l19.challenge', 'Lessons.programming.s4.l19.hint', ['al_presionar_tecla', 'crear_clon', 'al_comenzar_como_clon', 'mover_arriba', 'por_siempre'], 5, 4, 20, 2),
    pLesson('s4', 20, 'lesson', 'Lessons.programming.s4.l20.title', 'Lessons.programming.s4.l20.description', 'Lessons.programming.s4.l20.challenge', 'Lessons.programming.s4.l20.hint', ['si', 'tocando_borde', 'eliminar_clon'], 4, 3, 15, 1),
    pLesson('s4', 21, 'practice', 'Lessons.programming.s4.l21.title', 'Lessons.programming.s4.l21.description', 'Lessons.programming.s4.l21.challenge', 'Lessons.programming.s4.l21.hint', ['crear_clon', 'al_comenzar_como_clon', 'mover_abajo', 'si', 'tocando_borde', 'eliminar_clon', 'por_siempre'], 5, 4, 20, 2),
    pLesson('s4', 22, 'practice', 'Lessons.programming.s4.l22.title', 'Lessons.programming.s4.l22.description', 'Lessons.programming.s4.l22.challenge', 'Lessons.programming.s4.l22.hint', ['crear_clon', 'al_comenzar_como_clon', 'ir_a', 'aleatorio'], 5, 4, 20, 2),
    pLesson('s4', 23, 'practice', 'Lessons.programming.s4.l23.title', 'Lessons.programming.s4.l23.description', 'Lessons.programming.s4.l23.challenge', 'Lessons.programming.s4.l23.hint', ['crear_clon', 'al_comenzar_como_clon', 'si', 'tocando_objeto', 'cambiar_variable', 'eliminar_clon'], 6, 5, 25, 2),
    pLesson('s4', 24, 'practice', 'Lessons.programming.s4.l24.title', 'Lessons.programming.s4.l24.description', 'Lessons.programming.s4.l24.challenge', 'Lessons.programming.s4.l24.hint', ['crear_clon', 'al_comenzar_como_clon', 'si', 'tocando_objeto', 'cambiar_variable', 'eliminar_clon'], 6, 5, 25, 2),
    pLesson('s4', 25, 'practice', 'Lessons.programming.s4.l25.title', 'Lessons.programming.s4.l25.description', 'Lessons.programming.s4.l25.challenge', 'Lessons.programming.s4.l25.hint', ['crear_clon', 'aleatorio', 'si_sino', 'al_comenzar_como_clon'], 6, 5, 25, 2),
    pLesson('s4', 26, 'practice', 'Lessons.programming.s4.l26.title', 'Lessons.programming.s4.l26.description', 'Lessons.programming.s4.l26.challenge', 'Lessons.programming.s4.l26.hint', ['crear_clon', 'al_comenzar_como_clon', 'cambiar_variable', 'mover_abajo'], 6, 5, 25, 2),
    pLesson('s4', 27, 'practice', 'Lessons.programming.s4.l27.title', 'Lessons.programming.s4.l27.description', 'Lessons.programming.s4.l27.challenge', 'Lessons.programming.s4.l27.hint', ['crear_clon', 'al_comenzar_como_clon', 'si', 'tocando_objeto', 'eliminar_clon', 'cambiar_variable'], 7, 5, 30, 2),
    pLesson('s4', 28, 'practice', 'Lessons.programming.s4.l28.title', 'Lessons.programming.s4.l28.description', 'Lessons.programming.s4.l28.challenge', 'Lessons.programming.s4.l28.hint', ['por_siempre', 'repetir', 'crear_clon', 'esperar', 'al_comenzar_como_clon'], 7, 5, 30, 2),
    pLesson('s4', 29, 'practice', 'Lessons.programming.s4.l29.title', 'Lessons.programming.s4.l29.description', 'Lessons.programming.s4.l29.challenge', 'Lessons.programming.s4.l29.hint', ['al_presionar_tecla', 'crear_clon', 'al_comenzar_como_clon', 'si', 'tocando_objeto', 'eliminar_clon', 'cambiar_variable'], 7, 6, 30, 3),
    pLesson('s4', 30, 'challenge', 'Lessons.programming.s4.l30.title', 'Lessons.programming.s4.l30.description', 'Lessons.programming.s4.l30.challenge', 'Lessons.programming.s4.l30.hint', ['crear_clon', 'al_comenzar_como_clon', 'si', 'si_sino', 'tocando_objeto', 'cambiar_variable', 'fijar_variable', 'eliminar_clon', 'por_siempre', 'al_presionar_tecla'], 8, 6, 40, 3),

    // Fase 3: Mis Bloques / Funciones (31-40)
    pLesson('s4', 31, 'lesson', 'Lessons.programming.s4.l31.title', 'Lessons.programming.s4.l31.description', 'Lessons.programming.s4.l31.challenge', 'Lessons.programming.s4.l31.hint', ['definir_bloque'], 4, 3, 15, 1),
    pLesson('s4', 32, 'lesson', 'Lessons.programming.s4.l32.title', 'Lessons.programming.s4.l32.description', 'Lessons.programming.s4.l32.challenge', 'Lessons.programming.s4.l32.hint', ['definir_bloque', 'usar_bloque'], 4, 3, 15, 1),
    pLesson('s4', 33, 'lesson', 'Lessons.programming.s4.l33.title', 'Lessons.programming.s4.l33.description', 'Lessons.programming.s4.l33.challenge', 'Lessons.programming.s4.l33.hint', ['definir_bloque', 'parametro'], 5, 4, 20, 2),
    pLesson('s4', 34, 'practice', 'Lessons.programming.s4.l34.title', 'Lessons.programming.s4.l34.description', 'Lessons.programming.s4.l34.challenge', 'Lessons.programming.s4.l34.hint', ['definir_bloque', 'parametro', 'repetir', 'bajar_lapiz', 'girar_derecha_90'], 6, 5, 25, 2),
    pLesson('s4', 35, 'practice', 'Lessons.programming.s4.l35.title', 'Lessons.programming.s4.l35.description', 'Lessons.programming.s4.l35.challenge', 'Lessons.programming.s4.l35.hint', ['definir_bloque', 'usar_bloque'], 6, 5, 25, 2),
    pLesson('s4', 36, 'practice', 'Lessons.programming.s4.l36.title', 'Lessons.programming.s4.l36.description', 'Lessons.programming.s4.l36.challenge', 'Lessons.programming.s4.l36.hint', ['definir_bloque', 'fijar_variable', 'ir_a', 'mostrar'], 5, 4, 20, 2),
    pLesson('s4', 37, 'practice', 'Lessons.programming.s4.l37.title', 'Lessons.programming.s4.l37.description', 'Lessons.programming.s4.l37.challenge', 'Lessons.programming.s4.l37.hint', ['definir_bloque', 'cambiar_variable', 'tocar_sonido', 'si'], 5, 4, 20, 2),
    pLesson('s4', 38, 'practice', 'Lessons.programming.s4.l38.title', 'Lessons.programming.s4.l38.description', 'Lessons.programming.s4.l38.challenge', 'Lessons.programming.s4.l38.hint', ['definir_bloque', 'usar_bloque'], 6, 5, 25, 2),
    pLesson('s4', 39, 'practice', 'Lessons.programming.s4.l39.title', 'Lessons.programming.s4.l39.description', 'Lessons.programming.s4.l39.challenge', 'Lessons.programming.s4.l39.hint', ['definir_bloque', 'parametro', 'repetir', 'cambiar_disfraz', 'esperar'], 6, 5, 25, 2),
    pLesson('s4', 40, 'challenge', 'Lessons.programming.s4.l40.title', 'Lessons.programming.s4.l40.description', 'Lessons.programming.s4.l40.challenge', 'Lessons.programming.s4.l40.hint', ['definir_bloque', 'parametro', 'usar_bloque'], 8, 6, 40, 3),

    // Fase 4: Física Básica (41-50)
    pLesson('s4', 41, 'lesson', 'Lessons.programming.s4.l41.title', 'Lessons.programming.s4.l41.description', 'Lessons.programming.s4.l41.challenge', 'Lessons.programming.s4.l41.hint', ['crear_variable', 'cambiar_variable', 'por_siempre'], 5, 3, 15, 1),
    pLesson('s4', 42, 'lesson', 'Lessons.programming.s4.l42.title', 'Lessons.programming.s4.l42.description', 'Lessons.programming.s4.l42.challenge', 'Lessons.programming.s4.l42.hint', ['cambiar_variable', 'por_siempre'], 5, 3, 15, 1),
    pLesson('s4', 43, 'lesson', 'Lessons.programming.s4.l43.title', 'Lessons.programming.s4.l43.description', 'Lessons.programming.s4.l43.challenge', 'Lessons.programming.s4.l43.hint', ['si', 'tocando_color', 'fijar_variable'], 5, 4, 20, 2),
    pLesson('s4', 44, 'lesson', 'Lessons.programming.s4.l44.title', 'Lessons.programming.s4.l44.description', 'Lessons.programming.s4.l44.challenge', 'Lessons.programming.s4.l44.hint', ['al_presionar_tecla', 'fijar_variable', 'si', 'tocando_color'], 5, 4, 20, 2),
    pLesson('s4', 45, 'practice', 'Lessons.programming.s4.l45.title', 'Lessons.programming.s4.l45.description', 'Lessons.programming.s4.l45.challenge', 'Lessons.programming.s4.l45.hint', ['si', 'operador_y', 'tecla_presionada', 'tocando_color', 'fijar_variable'], 5, 4, 20, 2),
    pLesson('s4', 46, 'practice', 'Lessons.programming.s4.l46.title', 'Lessons.programming.s4.l46.description', 'Lessons.programming.s4.l46.challenge', 'Lessons.programming.s4.l46.hint', ['al_presionar_tecla', 'mover_derecha', 'mover_izquierda', 'fijar_variable', 'por_siempre'], 6, 5, 25, 2),
    pLesson('s4', 47, 'practice', 'Lessons.programming.s4.l47.title', 'Lessons.programming.s4.l47.description', 'Lessons.programming.s4.l47.challenge', 'Lessons.programming.s4.l47.hint', ['si', 'tocando_color', 'fijar_variable', 'por_siempre'], 6, 5, 25, 2),
    pLesson('s4', 48, 'practice', 'Lessons.programming.s4.l48.title', 'Lessons.programming.s4.l48.description', 'Lessons.programming.s4.l48.challenge', 'Lessons.programming.s4.l48.hint', ['si', 'tocando_color', 'por_siempre', 'mover_derecha', 'rebotar'], 7, 5, 30, 2),
    pLesson('s4', 49, 'practice', 'Lessons.programming.s4.l49.title', 'Lessons.programming.s4.l49.description', 'Lessons.programming.s4.l49.challenge', 'Lessons.programming.s4.l49.hint', ['si', 'operador_mayor', 'cambiar_variable', 'fijar_variable', 'tecla_presionada'], 6, 5, 25, 2),
    pLesson('s4', 50, 'challenge', 'Lessons.programming.s4.l50.title', 'Lessons.programming.s4.l50.description', 'Lessons.programming.s4.l50.challenge', 'Lessons.programming.s4.l50.hint', ['fijar_variable', 'cambiar_variable', 'si', 'si_sino', 'tocando_color', 'tecla_presionada', 'por_siempre', 'al_presionar_tecla'], 8, 6, 40, 3),

    // Fase 5: Proyecto Final de Curso (51-60)
    pLesson('s4', 51, 'lesson', 'Lessons.programming.s4.l51.title', 'Lessons.programming.s4.l51.description', 'Lessons.programming.s4.l51.challenge', 'Lessons.programming.s4.l51.hint', ['decir'], 4, 2, 10, 1),
    pLesson('s4', 52, 'practice', 'Lessons.programming.s4.l52.title', 'Lessons.programming.s4.l52.description', 'Lessons.programming.s4.l52.challenge', 'Lessons.programming.s4.l52.hint', ['cambiar_fondo', 'al_presionar_tecla', 'enviar_mensaje', 'decir'], 5, 4, 20, 2),
    pLesson('s4', 53, 'practice', 'Lessons.programming.s4.l53.title', 'Lessons.programming.s4.l53.description', 'Lessons.programming.s4.l53.challenge', 'Lessons.programming.s4.l53.hint', ['al_recibir_mensaje', 'cambiar_fondo', 'fijar_variable', 'ir_a'], 5, 4, 20, 2),
    pLesson('s4', 54, 'practice', 'Lessons.programming.s4.l54.title', 'Lessons.programming.s4.l54.description', 'Lessons.programming.s4.l54.challenge', 'Lessons.programming.s4.l54.hint', ['por_siempre', 'si', 'tocando_color', 'fijar_variable', 'cambiar_variable', 'al_presionar_tecla'], 6, 5, 25, 2),
    pLesson('s4', 55, 'practice', 'Lessons.programming.s4.l55.title', 'Lessons.programming.s4.l55.description', 'Lessons.programming.s4.l55.challenge', 'Lessons.programming.s4.l55.hint', ['crear_clon', 'al_comenzar_como_clon', 'si', 'tocando_objeto', 'cambiar_variable', 'eliminar_clon'], 6, 5, 25, 2),
    pLesson('s4', 56, 'practice', 'Lessons.programming.s4.l56.title', 'Lessons.programming.s4.l56.description', 'Lessons.programming.s4.l56.challenge', 'Lessons.programming.s4.l56.hint', ['crear_clon', 'al_comenzar_como_clon', 'por_siempre', 'mover_derecha', 'si', 'tocando_borde', 'rebotar', 'tocando_objeto', 'cambiar_variable'], 7, 5, 30, 2),
    pLesson('s4', 57, 'practice', 'Lessons.programming.s4.l57.title', 'Lessons.programming.s4.l57.description', 'Lessons.programming.s4.l57.challenge', 'Lessons.programming.s4.l57.hint', ['si', 'tocando_color', 'enviar_mensaje', 'al_recibir_mensaje', 'cambiar_fondo'], 6, 5, 25, 2),
    pLesson('s4', 58, 'practice', 'Lessons.programming.s4.l58.title', 'Lessons.programming.s4.l58.description', 'Lessons.programming.s4.l58.challenge', 'Lessons.programming.s4.l58.hint', ['si', 'operador_igual', 'enviar_mensaje', 'cambiar_fondo', 'decir', 'detener_todo'], 5, 4, 20, 2),
    pLesson('s4', 59, 'practice', 'Lessons.programming.s4.l59.title', 'Lessons.programming.s4.l59.description', 'Lessons.programming.s4.l59.challenge', 'Lessons.programming.s4.l59.hint', ['bandera_verde'], 6, 4, 25, 2),
    pLesson('s4', 60, 'challenge', 'Lessons.programming.s4.l60.title', 'Lessons.programming.s4.l60.description', 'Lessons.programming.s4.l60.challenge', 'Lessons.programming.s4.l60.hint', ['bandera_verde', 'por_siempre', 'si', 'si_sino', 'crear_clon', 'al_comenzar_como_clon', 'eliminar_clon', 'definir_bloque', 'fijar_variable', 'cambiar_variable', 'tocando_color', 'tocando_objeto', 'enviar_mensaje', 'al_recibir_mensaje', 'cambiar_fondo', 'tocar_sonido'], 10, 10, 100, 5),
];
