// Section 2: El Mago del Tiempo (Bucles y Eventos)
// 60 lessons

import { MicroLesson, LessonType } from './microLessonSystem';
import { pLesson } from './programmingLessons';

export const SECTION_2_LESSONS: MicroLesson[] = [
    // Fase 1: Bucles "Repetir X veces" (1-15)
    pLesson('s2', 1, 'lesson', 'Lessons.programming.s2.l1.title', 'Lessons.programming.s2.l1.description', 'Lessons.programming.s2.l1.challenge', 'Lessons.programming.s2.l1.hint', ['mover_derecha'], 4, 2, 10, 1),
    pLesson('s2', 2, 'lesson', 'Lessons.programming.s2.l2.title', 'Lessons.programming.s2.l2.description', 'Lessons.programming.s2.l2.challenge', 'Lessons.programming.s2.l2.hint', ['repetir', 'mover_derecha'], 4, 3, 15, 1),
    pLesson('s2', 3, 'practice', 'Lessons.programming.s2.l3.title', 'Lessons.programming.s2.l3.description', 'Lessons.programming.s2.l3.challenge', 'Lessons.programming.s2.l3.hint', ['repetir', 'mover_derecha', 'girar_derecha_90', 'bajar_lapiz'], 5, 4, 20, 2),
    pLesson('s2', 4, 'practice', 'Lessons.programming.s2.l4.title', 'Lessons.programming.s2.l4.description', 'Lessons.programming.s2.l4.challenge', 'Lessons.programming.s2.l4.hint', ['repetir', 'mover_derecha', 'mover_arriba'], 5, 4, 20, 2),
    pLesson('s2', 5, 'practice', 'Lessons.programming.s2.l5.title', 'Lessons.programming.s2.l5.description', 'Lessons.programming.s2.l5.challenge', 'Lessons.programming.s2.l5.hint', ['repetir', 'mover_derecha', 'girar_derecha_90', 'bajar_lapiz'], 5, 4, 20, 2),
    pLesson('s2', 6, 'practice', 'Lessons.programming.s2.l6.title', 'Lessons.programming.s2.l6.description', 'Lessons.programming.s2.l6.challenge', 'Lessons.programming.s2.l6.hint', ['repetir', 'mover_derecha', 'girar_derecha_90', 'bajar_lapiz'], 5, 5, 25, 2),
    pLesson('s2', 7, 'lesson', 'Lessons.programming.s2.l7.title', 'Lessons.programming.s2.l7.description', 'Lessons.programming.s2.l7.challenge', 'Lessons.programming.s2.l7.hint', ['repetir', 'mover_derecha', 'girar_derecha_90', 'bajar_lapiz'], 5, 4, 20, 2),
    pLesson('s2', 8, 'lesson', 'Lessons.programming.s2.l8.title', 'Lessons.programming.s2.l8.description', 'Lessons.programming.s2.l8.challenge', 'Lessons.programming.s2.l8.hint', ['repetir', 'mover_derecha', 'girar_derecha_90', 'bajar_lapiz'], 6, 5, 25, 2),
    pLesson('s2', 9, 'practice', 'Lessons.programming.s2.l9.title', 'Lessons.programming.s2.l9.description', 'Lessons.programming.s2.l9.challenge', 'Lessons.programming.s2.l9.hint', ['repetir', 'mover_derecha', 'girar_derecha_90', 'bajar_lapiz'], 6, 5, 25, 2),
    pLesson('s2', 10, 'practice', 'Lessons.programming.s2.l10.title', 'Lessons.programming.s2.l10.description', 'Lessons.programming.s2.l10.challenge', 'Lessons.programming.s2.l10.hint', ['repetir', 'mover_derecha', 'girar_derecha_90', 'bajar_lapiz'], 6, 5, 25, 2),
    pLesson('s2', 11, 'practice', 'Lessons.programming.s2.l11.title', 'Lessons.programming.s2.l11.description', 'Lessons.programming.s2.l11.challenge', 'Lessons.programming.s2.l11.hint', ['repetir', 'mover_derecha', 'girar_derecha_90', 'bajar_lapiz'], 6, 5, 25, 2),
    pLesson('s2', 12, 'practice', 'Lessons.programming.s2.l12.title', 'Lessons.programming.s2.l12.description', 'Lessons.programming.s2.l12.challenge', 'Lessons.programming.s2.l12.hint', ['repetir', 'mover_derecha', 'girar_derecha_90', 'bajar_lapiz', 'color_rojo'], 7, 5, 30, 2),
    pLesson('s2', 13, 'practice', 'Lessons.programming.s2.l13.title', 'Lessons.programming.s2.l13.description', 'Lessons.programming.s2.l13.challenge', 'Lessons.programming.s2.l13.hint', ['repetir', 'mover_derecha', 'mover_abajo', 'bajar_lapiz', 'subir_lapiz'], 7, 5, 30, 3),
    pLesson('s2', 14, 'practice', 'Lessons.programming.s2.l14.title', 'Lessons.programming.s2.l14.description', 'Lessons.programming.s2.l14.challenge', 'Lessons.programming.s2.l14.hint', ['repetir', 'cambiar_disfraz', 'mover_derecha', 'tocar_nota'], 5, 4, 25, 2),
    pLesson('s2', 15, 'challenge', 'Lessons.programming.s2.l15.title', 'Lessons.programming.s2.l15.description', 'Lessons.programming.s2.l15.challenge', 'Lessons.programming.s2.l15.hint', ['repetir', 'mover_derecha', 'girar_derecha_90', 'bajar_lapiz', 'color_rojo', 'color_azul', 'color_verde'], 8, 6, 40, 3),

    // Fase 2: Bucles "Por siempre" (16-25)
    pLesson('s2', 16, 'lesson', 'Lessons.programming.s2.l16.title', 'Lessons.programming.s2.l16.description', 'Lessons.programming.s2.l16.challenge', 'Lessons.programming.s2.l16.hint', ['por_siempre', 'mover_derecha'], 4, 3, 15, 1),
    pLesson('s2', 17, 'lesson', 'Lessons.programming.s2.l17.title', 'Lessons.programming.s2.l17.description', 'Lessons.programming.s2.l17.challenge', 'Lessons.programming.s2.l17.hint', ['por_siempre', 'girar_derecha_90'], 4, 3, 15, 1),
    pLesson('s2', 18, 'practice', 'Lessons.programming.s2.l18.title', 'Lessons.programming.s2.l18.description', 'Lessons.programming.s2.l18.challenge', 'Lessons.programming.s2.l18.hint', ['por_siempre', 'cambiar_disfraz', 'esperar'], 5, 4, 20, 2),
    pLesson('s2', 19, 'practice', 'Lessons.programming.s2.l19.title', 'Lessons.programming.s2.l19.description', 'Lessons.programming.s2.l19.challenge', 'Lessons.programming.s2.l19.hint', ['por_siempre', 'efecto_fantasma', 'esperar'], 5, 4, 20, 2),
    pLesson('s2', 20, 'practice', 'Lessons.programming.s2.l20.title', 'Lessons.programming.s2.l20.description', 'Lessons.programming.s2.l20.challenge', 'Lessons.programming.s2.l20.hint', ['por_siempre', 'cambiar_tamaño', 'esperar'], 5, 4, 20, 2),
    pLesson('s2', 21, 'practice', 'Lessons.programming.s2.l21.title', 'Lessons.programming.s2.l21.description', 'Lessons.programming.s2.l21.challenge', 'Lessons.programming.s2.l21.hint', ['por_siempre', 'mover_izquierda', 'cambiar_fondo'], 5, 4, 20, 2),
    pLesson('s2', 22, 'practice', 'Lessons.programming.s2.l22.title', 'Lessons.programming.s2.l22.description', 'Lessons.programming.s2.l22.challenge', 'Lessons.programming.s2.l22.hint', ['por_siempre', 'girar_derecha_90', 'cambiar_tamaño', 'esperar'], 5, 4, 20, 2),
    pLesson('s2', 23, 'practice', 'Lessons.programming.s2.l23.title', 'Lessons.programming.s2.l23.description', 'Lessons.programming.s2.l23.challenge', 'Lessons.programming.s2.l23.hint', ['por_siempre', 'efecto_fantasma', 'esperar'], 5, 4, 20, 2),
    pLesson('s2', 24, 'practice', 'Lessons.programming.s2.l24.title', 'Lessons.programming.s2.l24.description', 'Lessons.programming.s2.l24.challenge', 'Lessons.programming.s2.l24.hint', ['por_siempre', 'girar_derecha_90', 'efecto_fantasma', 'mover_izquierda'], 6, 5, 25, 2),
    pLesson('s2', 25, 'challenge', 'Lessons.programming.s2.l25.title', 'Lessons.programming.s2.l25.description', 'Lessons.programming.s2.l25.challenge', 'Lessons.programming.s2.l25.hint', ['por_siempre', 'mover_derecha', 'mover_izquierda', 'cambiar_disfraz', 'esperar'], 7, 6, 35, 3),

    // Fase 3: Eventos de Teclado y Ratón (26-40)
    pLesson('s2', 26, 'lesson', 'Lessons.programming.s2.l26.title', 'Lessons.programming.s2.l26.description', 'Lessons.programming.s2.l26.challenge', 'Lessons.programming.s2.l26.hint', ['bandera_verde', 'decir'], 3, 2, 10, 1),
    pLesson('s2', 27, 'lesson', 'Lessons.programming.s2.l27.title', 'Lessons.programming.s2.l27.description', 'Lessons.programming.s2.l27.challenge', 'Lessons.programming.s2.l27.hint', ['al_presionar_tecla', 'mover_arriba'], 4, 3, 15, 1),
    pLesson('s2', 28, 'lesson', 'Lessons.programming.s2.l28.title', 'Lessons.programming.s2.l28.description', 'Lessons.programming.s2.l28.challenge', 'Lessons.programming.s2.l28.hint', ['al_presionar_tecla', 'mover_arriba', 'mover_abajo'], 4, 3, 15, 1),
    pLesson('s2', 29, 'practice', 'Lessons.programming.s2.l29.title', 'Lessons.programming.s2.l29.description', 'Lessons.programming.s2.l29.challenge', 'Lessons.programming.s2.l29.hint', ['al_presionar_tecla', 'mover_derecha', 'mover_izquierda', 'mover_arriba', 'mover_abajo'], 5, 4, 20, 2),
    pLesson('s2', 30, 'lesson', 'Lessons.programming.s2.l30.title', 'Lessons.programming.s2.l30.description', 'Lessons.programming.s2.l30.challenge', 'Lessons.programming.s2.l30.hint', ['por_siempre', 'apuntar_hacia', 'mover_derecha'], 5, 3, 15, 1),
    pLesson('s2', 31, 'practice', 'Lessons.programming.s2.l31.title', 'Lessons.programming.s2.l31.description', 'Lessons.programming.s2.l31.challenge', 'Lessons.programming.s2.l31.hint', ['al_hacer_click', 'decir'], 4, 3, 15, 1),
    pLesson('s2', 32, 'practice', 'Lessons.programming.s2.l32.title', 'Lessons.programming.s2.l32.description', 'Lessons.programming.s2.l32.challenge', 'Lessons.programming.s2.l32.hint', ['al_hacer_click', 'esconder'], 4, 3, 15, 2),
    pLesson('s2', 33, 'practice', 'Lessons.programming.s2.l33.title', 'Lessons.programming.s2.l33.description', 'Lessons.programming.s2.l33.challenge', 'Lessons.programming.s2.l33.hint', ['al_hacer_click', 'tocar_sonido'], 5, 4, 20, 2),
    pLesson('s2', 34, 'practice', 'Lessons.programming.s2.l34.title', 'Lessons.programming.s2.l34.description', 'Lessons.programming.s2.l34.challenge', 'Lessons.programming.s2.l34.hint', ['al_hacer_click', 'tocar_nota'], 6, 5, 25, 2),
    pLesson('s2', 35, 'practice', 'Lessons.programming.s2.l35.title', 'Lessons.programming.s2.l35.description', 'Lessons.programming.s2.l35.challenge', 'Lessons.programming.s2.l35.hint', ['al_hacer_click', 'mover_derecha', 'mover_arriba'], 6, 5, 25, 2),
    pLesson('s2', 36, 'practice', 'Lessons.programming.s2.l36.title', 'Lessons.programming.s2.l36.description', 'Lessons.programming.s2.l36.challenge', 'Lessons.programming.s2.l36.hint', ['al_presionar_tecla', 'mover_derecha', 'cambiar_disfraz', 'por_siempre'], 6, 5, 25, 2),
    pLesson('s2', 37, 'practice', 'Lessons.programming.s2.l37.title', 'Lessons.programming.s2.l37.description', 'Lessons.programming.s2.l37.challenge', 'Lessons.programming.s2.l37.hint', ['por_siempre', 'apuntar_hacia', 'mover_derecha', 'cambiar_disfraz'], 5, 4, 20, 2),
    pLesson('s2', 38, 'practice', 'Lessons.programming.s2.l38.title', 'Lessons.programming.s2.l38.description', 'Lessons.programming.s2.l38.challenge', 'Lessons.programming.s2.l38.hint', ['al_hacer_click', 'apuntar_hacia', 'mover_derecha', 'esconder'], 6, 5, 25, 2),
    pLesson('s2', 39, 'practice', 'Lessons.programming.s2.l39.title', 'Lessons.programming.s2.l39.description', 'Lessons.programming.s2.l39.challenge', 'Lessons.programming.s2.l39.hint', ['al_presionar_tecla', 'por_siempre', 'mover_arriba', 'mover_abajo', 'mover_izquierda'], 7, 5, 30, 2),
    pLesson('s2', 40, 'challenge', 'Lessons.programming.s2.l40.title', 'Lessons.programming.s2.l40.description', 'Lessons.programming.s2.l40.challenge', 'Lessons.programming.s2.l40.hint', ['al_presionar_tecla', 'al_hacer_click', 'por_siempre', 'mover_derecha', 'mover_arriba', 'cambiar_disfraz', 'tocar_sonido'], 8, 6, 40, 3),

    // Fase 4: Interacción entre Objetos (41-50)
    pLesson('s2', 41, 'lesson', 'Lessons.programming.s2.l41.title', 'Lessons.programming.s2.l41.description', 'Lessons.programming.s2.l41.challenge', 'Lessons.programming.s2.l41.hint', ['enviar_mensaje', 'al_presionar_tecla'], 4, 3, 15, 1),
    pLesson('s2', 42, 'lesson', 'Lessons.programming.s2.l42.title', 'Lessons.programming.s2.l42.description', 'Lessons.programming.s2.l42.challenge', 'Lessons.programming.s2.l42.hint', ['al_recibir_mensaje', 'mover_derecha'], 4, 3, 15, 1),
    pLesson('s2', 43, 'practice', 'Lessons.programming.s2.l43.title', 'Lessons.programming.s2.l43.description', 'Lessons.programming.s2.l43.challenge', 'Lessons.programming.s2.l43.hint', ['enviar_mensaje', 'al_recibir_mensaje', 'decir', 'esperar'], 5, 4, 20, 2),
    pLesson('s2', 44, 'practice', 'Lessons.programming.s2.l44.title', 'Lessons.programming.s2.l44.description', 'Lessons.programming.s2.l44.challenge', 'Lessons.programming.s2.l44.hint', ['enviar_mensaje', 'al_recibir_mensaje', 'decir'], 5, 4, 20, 2),
    pLesson('s2', 45, 'practice', 'Lessons.programming.s2.l45.title', 'Lessons.programming.s2.l45.description', 'Lessons.programming.s2.l45.challenge', 'Lessons.programming.s2.l45.hint', ['enviar_mensaje', 'al_recibir_mensaje', 'cambiar_fondo'], 5, 4, 20, 2),
    pLesson('s2', 46, 'practice', 'Lessons.programming.s2.l46.title', 'Lessons.programming.s2.l46.description', 'Lessons.programming.s2.l46.challenge', 'Lessons.programming.s2.l46.hint', ['al_hacer_click', 'enviar_mensaje', 'al_recibir_mensaje', 'tocar_nota'], 6, 5, 25, 2),
    pLesson('s2', 47, 'practice', 'Lessons.programming.s2.l47.title', 'Lessons.programming.s2.l47.description', 'Lessons.programming.s2.l47.challenge', 'Lessons.programming.s2.l47.hint', ['enviar_mensaje', 'al_recibir_mensaje', 'cambiar_disfraz', 'esperar'], 6, 5, 25, 2),
    pLesson('s2', 48, 'practice', 'Lessons.programming.s2.l48.title', 'Lessons.programming.s2.l48.description', 'Lessons.programming.s2.l48.challenge', 'Lessons.programming.s2.l48.hint', ['al_presionar_tecla', 'enviar_mensaje', 'al_recibir_mensaje', 'cambiar_fondo', 'decir'], 6, 5, 25, 2),
    pLesson('s2', 49, 'practice', 'Lessons.programming.s2.l49.title', 'Lessons.programming.s2.l49.description', 'Lessons.programming.s2.l49.challenge', 'Lessons.programming.s2.l49.hint', ['por_siempre', 'tocando_objeto', 'tocar_sonido'], 5, 4, 20, 2),
    pLesson('s2', 50, 'challenge', 'Lessons.programming.s2.l50.title', 'Lessons.programming.s2.l50.description', 'Lessons.programming.s2.l50.challenge', 'Lessons.programming.s2.l50.hint', ['bandera_verde', 'enviar_mensaje', 'al_recibir_mensaje', 'cambiar_disfraz', 'tocar_nota', 'por_siempre'], 7, 6, 35, 3),

    // Fase 5: Proyecto Final (51-60)
    pLesson('s2', 51, 'lesson', 'Lessons.programming.s2.l51.title', 'Lessons.programming.s2.l51.description', 'Lessons.programming.s2.l51.challenge', 'Lessons.programming.s2.l51.hint', ['decir'], 4, 2, 10, 1),
    pLesson('s2', 52, 'practice', 'Lessons.programming.s2.l52.title', 'Lessons.programming.s2.l52.description', 'Lessons.programming.s2.l52.challenge', 'Lessons.programming.s2.l52.hint', ['cambiar_fondo', 'bandera_verde'], 4, 3, 15, 1),
    pLesson('s2', 53, 'practice', 'Lessons.programming.s2.l53.title', 'Lessons.programming.s2.l53.description', 'Lessons.programming.s2.l53.challenge', 'Lessons.programming.s2.l53.hint', ['por_siempre', 'ir_a_aleatorio', 'esperar'], 5, 4, 20, 2),
    pLesson('s2', 54, 'practice', 'Lessons.programming.s2.l54.title', 'Lessons.programming.s2.l54.description', 'Lessons.programming.s2.l54.challenge', 'Lessons.programming.s2.l54.hint', ['al_hacer_click', 'decir', 'tocar_sonido'], 5, 4, 20, 2),
    pLesson('s2', 55, 'practice', 'Lessons.programming.s2.l55.title', 'Lessons.programming.s2.l55.description', 'Lessons.programming.s2.l55.challenge', 'Lessons.programming.s2.l55.hint', ['por_siempre', 'ir_a_aleatorio', 'esperar'], 5, 4, 20, 2),
    pLesson('s2', 56, 'practice', 'Lessons.programming.s2.l56.title', 'Lessons.programming.s2.l56.description', 'Lessons.programming.s2.l56.challenge', 'Lessons.programming.s2.l56.hint', ['al_hacer_click', 'tocar_sonido'], 4, 3, 15, 2),
    pLesson('s2', 57, 'practice', 'Lessons.programming.s2.l57.title', 'Lessons.programming.s2.l57.description', 'Lessons.programming.s2.l57.challenge', 'Lessons.programming.s2.l57.hint', ['al_hacer_click', 'repetir', 'girar_derecha_90', 'cambiar_tamaño'], 5, 4, 20, 2),
    pLesson('s2', 58, 'practice', 'Lessons.programming.s2.l58.title', 'Lessons.programming.s2.l58.description', 'Lessons.programming.s2.l58.challenge', 'Lessons.programming.s2.l58.hint', ['enviar_mensaje', 'al_recibir_mensaje', 'cambiar_fondo', 'decir'], 6, 5, 25, 2),
    pLesson('s2', 59, 'practice', 'Lessons.programming.s2.l59.title', 'Lessons.programming.s2.l59.description', 'Lessons.programming.s2.l59.challenge', 'Lessons.programming.s2.l59.hint', ['bandera_verde', 'decir', 'esperar', 'tocar_sonido', 'por_siempre'], 5, 4, 20, 2),
    pLesson('s2', 60, 'challenge', 'Lessons.programming.s2.l60.title', 'Lessons.programming.s2.l60.description', 'Lessons.programming.s2.l60.challenge', 'Lessons.programming.s2.l60.hint', ['bandera_verde', 'por_siempre', 'al_hacer_click', 'ir_a_aleatorio', 'enviar_mensaje', 'al_recibir_mensaje', 'tocar_sonido', 'cambiar_disfraz'], 8, 8, 50, 5),
];
