// Section 3: El Detective Lógico (Condicionales y Sensores)
// 60 lessons

import { MicroLesson, LessonType } from './microLessonSystem';
import { pLesson } from './programmingLessons';

export const SECTION_3_LESSONS: MicroLesson[] = [
    // Fase 1: Sensores de Entorno (1-10)
    pLesson('s3', 1, 'lesson', 'Lessons.programming.s3.l1.title', 'Lessons.programming.s3.l1.description', 'Lessons.programming.s3.l1.challenge', 'Lessons.programming.s3.l1.hint', ['tocando_borde'], 3, 2, 10, 1),
    pLesson('s3', 2, 'lesson', 'Lessons.programming.s3.l2.title', 'Lessons.programming.s3.l2.description', 'Lessons.programming.s3.l2.challenge', 'Lessons.programming.s3.l2.hint', ['tocando_puntero'], 3, 2, 10, 1),
    pLesson('s3', 3, 'lesson', 'Lessons.programming.s3.l3.title', 'Lessons.programming.s3.l3.description', 'Lessons.programming.s3.l3.challenge', 'Lessons.programming.s3.l3.hint', ['tocando_color'], 4, 3, 15, 1),
    pLesson('s3', 4, 'lesson', 'Lessons.programming.s3.l4.title', 'Lessons.programming.s3.l4.description', 'Lessons.programming.s3.l4.challenge', 'Lessons.programming.s3.l4.hint', ['tocando_color'], 4, 3, 15, 1),
    pLesson('s3', 5, 'lesson', 'Lessons.programming.s3.l5.title', 'Lessons.programming.s3.l5.description', 'Lessons.programming.s3.l5.challenge', 'Lessons.programming.s3.l5.hint', ['distancia_a', 'decir'], 4, 3, 15, 1),
    pLesson('s3', 6, 'practice', 'Lessons.programming.s3.l6.title', 'Lessons.programming.s3.l6.description', 'Lessons.programming.s3.l6.challenge', 'Lessons.programming.s3.l6.hint', ['tocando_color', 'decir', 'por_siempre'], 5, 4, 20, 2),
    pLesson('s3', 7, 'practice', 'Lessons.programming.s3.l7.title', 'Lessons.programming.s3.l7.description', 'Lessons.programming.s3.l7.challenge', 'Lessons.programming.s3.l7.hint', ['distancia_a', 'cambiar_disfraz', 'por_siempre'], 5, 4, 20, 2),
    pLesson('s3', 8, 'practice', 'Lessons.programming.s3.l8.title', 'Lessons.programming.s3.l8.description', 'Lessons.programming.s3.l8.challenge', 'Lessons.programming.s3.l8.hint', ['tocando_color', 'decir', 'por_siempre', 'al_presionar_tecla'], 6, 5, 25, 2),
    pLesson('s3', 9, 'practice', 'Lessons.programming.s3.l9.title', 'Lessons.programming.s3.l9.description', 'Lessons.programming.s3.l9.challenge', 'Lessons.programming.s3.l9.hint', ['tocando_borde', 'tocar_sonido', 'por_siempre'], 5, 4, 20, 2),
    pLesson('s3', 10, 'challenge', 'Lessons.programming.s3.l10.title', 'Lessons.programming.s3.l10.description', 'Lessons.programming.s3.l10.challenge', 'Lessons.programming.s3.l10.hint', ['tocando_color', 'tocando_borde', 'distancia_a', 'decir', 'por_siempre'], 7, 6, 35, 3),

    // Fase 2: Si... entonces (If) (11-25)
    pLesson('s3', 11, 'lesson', 'Lessons.programming.s3.l11.title', 'Lessons.programming.s3.l11.description', 'Lessons.programming.s3.l11.challenge', 'Lessons.programming.s3.l11.hint', ['si', 'tocando_borde', 'rebotar', 'por_siempre'], 4, 3, 15, 1),
    pLesson('s3', 12, 'lesson', 'Lessons.programming.s3.l12.title', 'Lessons.programming.s3.l12.description', 'Lessons.programming.s3.l12.challenge', 'Lessons.programming.s3.l12.hint', ['si', 'tocando_color', 'ir_a'], 4, 3, 15, 1),
    pLesson('s3', 13, 'practice', 'Lessons.programming.s3.l13.title', 'Lessons.programming.s3.l13.description', 'Lessons.programming.s3.l13.challenge', 'Lessons.programming.s3.l13.hint', ['si', 'tocando_color', 'tocar_sonido'], 5, 4, 20, 2),
    pLesson('s3', 14, 'practice', 'Lessons.programming.s3.l14.title', 'Lessons.programming.s3.l14.description', 'Lessons.programming.s3.l14.challenge', 'Lessons.programming.s3.l14.hint', ['si', 'distancia_a', 'esconder'], 5, 4, 20, 2),
    pLesson('s3', 15, 'lesson', 'Lessons.programming.s3.l15.title', 'Lessons.programming.s3.l15.description', 'Lessons.programming.s3.l15.challenge', 'Lessons.programming.s3.l15.hint', ['si', 'tecla_presionada', 'detener_todo'], 4, 3, 15, 1),
    pLesson('s3', 16, 'practice', 'Lessons.programming.s3.l16.title', 'Lessons.programming.s3.l16.description', 'Lessons.programming.s3.l16.challenge', 'Lessons.programming.s3.l16.hint', ['por_siempre', 'si', 'tocando_borde', 'rebotar', 'mover_derecha'], 5, 4, 20, 2),
    pLesson('s3', 17, 'practice', 'Lessons.programming.s3.l17.title', 'Lessons.programming.s3.l17.description', 'Lessons.programming.s3.l17.challenge', 'Lessons.programming.s3.l17.hint', ['si', 'tocando_color', 'ir_a', 'al_presionar_tecla', 'mover_derecha'], 6, 5, 25, 2),
    pLesson('s3', 18, 'practice', 'Lessons.programming.s3.l18.title', 'Lessons.programming.s3.l18.description', 'Lessons.programming.s3.l18.challenge', 'Lessons.programming.s3.l18.hint', ['si', 'tocando_color', 'ir_a', 'al_presionar_tecla'], 6, 5, 25, 2),
    pLesson('s3', 19, 'practice', 'Lessons.programming.s3.l19.title', 'Lessons.programming.s3.l19.description', 'Lessons.programming.s3.l19.challenge', 'Lessons.programming.s3.l19.hint', ['si', 'tocando_color', 'ir_a', 'al_presionar_tecla'], 7, 5, 30, 2),
    pLesson('s3', 20, 'practice', 'Lessons.programming.s3.l20.title', 'Lessons.programming.s3.l20.description', 'Lessons.programming.s3.l20.challenge', 'Lessons.programming.s3.l20.hint', ['si', 'tocando_objeto', 'esconder', 'tocar_sonido', 'por_siempre'], 6, 5, 25, 2),
    pLesson('s3', 21, 'practice', 'Lessons.programming.s3.l21.title', 'Lessons.programming.s3.l21.description', 'Lessons.programming.s3.l21.challenge', 'Lessons.programming.s3.l21.hint', ['si', 'tocando_color', 'decir', 'por_siempre'], 5, 4, 20, 2),
    pLesson('s3', 22, 'practice', 'Lessons.programming.s3.l22.title', 'Lessons.programming.s3.l22.description', 'Lessons.programming.s3.l22.challenge', 'Lessons.programming.s3.l22.hint', ['si', 'distancia_a', 'apuntar_hacia', 'mover_derecha', 'por_siempre'], 6, 5, 25, 2),
    pLesson('s3', 23, 'practice', 'Lessons.programming.s3.l23.title', 'Lessons.programming.s3.l23.description', 'Lessons.programming.s3.l23.challenge', 'Lessons.programming.s3.l23.hint', ['si', 'tocando_color', 'mover_arriba', 'por_siempre'], 5, 4, 20, 2),
    pLesson('s3', 24, 'practice', 'Lessons.programming.s3.l24.title', 'Lessons.programming.s3.l24.description', 'Lessons.programming.s3.l24.challenge', 'Lessons.programming.s3.l24.hint', ['si', 'distancia_a', 'cambiar_disfraz', 'por_siempre'], 5, 4, 20, 2),
    pLesson('s3', 25, 'challenge', 'Lessons.programming.s3.l25.title', 'Lessons.programming.s3.l25.description', 'Lessons.programming.s3.l25.challenge', 'Lessons.programming.s3.l25.hint', ['si', 'tocando_color', 'tocando_borde', 'ir_a', 'tocar_sonido', 'por_siempre', 'al_presionar_tecla'], 8, 6, 40, 3),

    // Fase 3: Si... sino (If/Else) (26-35)
    pLesson('s3', 26, 'lesson', 'Lessons.programming.s3.l26.title', 'Lessons.programming.s3.l26.description', 'Lessons.programming.s3.l26.challenge', 'Lessons.programming.s3.l26.hint', ['si_sino', 'cambiar_disfraz'], 4, 3, 15, 1),
    pLesson('s3', 27, 'lesson', 'Lessons.programming.s3.l27.title', 'Lessons.programming.s3.l27.description', 'Lessons.programming.s3.l27.challenge', 'Lessons.programming.s3.l27.hint', ['si_sino', 'preguntar', 'decir'], 5, 4, 20, 2),
    pLesson('s3', 28, 'practice', 'Lessons.programming.s3.l28.title', 'Lessons.programming.s3.l28.description', 'Lessons.programming.s3.l28.challenge', 'Lessons.programming.s3.l28.hint', ['si_sino', 'tocando_objeto', 'cambiar_disfraz', 'decir'], 5, 4, 20, 2),
    pLesson('s3', 29, 'practice', 'Lessons.programming.s3.l29.title', 'Lessons.programming.s3.l29.description', 'Lessons.programming.s3.l29.challenge', 'Lessons.programming.s3.l29.hint', ['si_sino', 'cambiar_disfraz', 'mover_derecha', 'esperar'], 5, 4, 20, 2),
    pLesson('s3', 30, 'practice', 'Lessons.programming.s3.l30.title', 'Lessons.programming.s3.l30.description', 'Lessons.programming.s3.l30.challenge', 'Lessons.programming.s3.l30.hint', ['si_sino', 'tocando_objeto', 'cambiar_tamaño', 'esperar', 'por_siempre'], 6, 5, 25, 2),
    pLesson('s3', 31, 'practice', 'Lessons.programming.s3.l31.title', 'Lessons.programming.s3.l31.description', 'Lessons.programming.s3.l31.challenge', 'Lessons.programming.s3.l31.hint', ['si_sino', 'preguntar', 'decir'], 5, 4, 20, 2),
    pLesson('s3', 32, 'practice', 'Lessons.programming.s3.l32.title', 'Lessons.programming.s3.l32.description', 'Lessons.programming.s3.l32.challenge', 'Lessons.programming.s3.l32.hint', ['si_sino', 'preguntar', 'decir'], 6, 5, 25, 2),
    pLesson('s3', 33, 'practice', 'Lessons.programming.s3.l33.title', 'Lessons.programming.s3.l33.description', 'Lessons.programming.s3.l33.challenge', 'Lessons.programming.s3.l33.hint', ['si_sino', 'preguntar', 'decir', 'tocar_sonido'], 6, 5, 25, 2),
    pLesson('s3', 34, 'practice', 'Lessons.programming.s3.l34.title', 'Lessons.programming.s3.l34.description', 'Lessons.programming.s3.l34.challenge', 'Lessons.programming.s3.l34.hint', ['si_sino', 'preguntar', 'decir'], 6, 5, 25, 2),
    pLesson('s3', 35, 'challenge', 'Lessons.programming.s3.l35.title', 'Lessons.programming.s3.l35.description', 'Lessons.programming.s3.l35.challenge', 'Lessons.programming.s3.l35.hint', ['si_sino', 'preguntar', 'decir', 'tocar_sonido', 'enviar_mensaje'], 8, 6, 40, 3),

    // Fase 4: Operadores Matemáticos y Lógicos (36-50)
    pLesson('s3', 36, 'lesson', 'Lessons.programming.s3.l36.title', 'Lessons.programming.s3.l36.description', 'Lessons.programming.s3.l36.challenge', 'Lessons.programming.s3.l36.hint', ['operador_suma', 'ir_a'], 4, 3, 15, 1),
    pLesson('s3', 37, 'lesson', 'Lessons.programming.s3.l37.title', 'Lessons.programming.s3.l37.description', 'Lessons.programming.s3.l37.challenge', 'Lessons.programming.s3.l37.hint', ['operador_resta', 'ir_a'], 4, 3, 15, 1),
    pLesson('s3', 38, 'lesson', 'Lessons.programming.s3.l38.title', 'Lessons.programming.s3.l38.description', 'Lessons.programming.s3.l38.challenge', 'Lessons.programming.s3.l38.hint', ['operador_mayor', 'si', 'decir'], 4, 3, 15, 1),
    pLesson('s3', 39, 'lesson', 'Lessons.programming.s3.l39.title', 'Lessons.programming.s3.l39.description', 'Lessons.programming.s3.l39.challenge', 'Lessons.programming.s3.l39.hint', ['operador_menor', 'si', 'decir'], 4, 3, 15, 1),
    pLesson('s3', 40, 'lesson', 'Lessons.programming.s3.l40.title', 'Lessons.programming.s3.l40.description', 'Lessons.programming.s3.l40.challenge', 'Lessons.programming.s3.l40.hint', ['operador_igual', 'si', 'preguntar', 'decir'], 4, 3, 15, 1),
    pLesson('s3', 41, 'practice', 'Lessons.programming.s3.l41.title', 'Lessons.programming.s3.l41.description', 'Lessons.programming.s3.l41.challenge', 'Lessons.programming.s3.l41.hint', ['aleatorio', 'decir'], 4, 3, 15, 2),
    pLesson('s3', 42, 'practice', 'Lessons.programming.s3.l42.title', 'Lessons.programming.s3.l42.description', 'Lessons.programming.s3.l42.challenge', 'Lessons.programming.s3.l42.hint', ['preguntar', 'operador_suma', 'decir'], 5, 4, 20, 2),
    pLesson('s3', 43, 'practice', 'Lessons.programming.s3.l43.title', 'Lessons.programming.s3.l43.description', 'Lessons.programming.s3.l43.challenge', 'Lessons.programming.s3.l43.hint', ['operador_mayor', 'operador_menor', 'si_sino', 'cambiar_disfraz', 'decir'], 5, 4, 20, 2),
    pLesson('s3', 44, 'lesson', 'Lessons.programming.s3.l44.title', 'Lessons.programming.s3.l44.description', 'Lessons.programming.s3.l44.challenge', 'Lessons.programming.s3.l44.hint', ['operador_y', 'si', 'tocando_color', 'tecla_presionada'], 5, 4, 20, 2),
    pLesson('s3', 45, 'lesson', 'Lessons.programming.s3.l45.title', 'Lessons.programming.s3.l45.description', 'Lessons.programming.s3.l45.challenge', 'Lessons.programming.s3.l45.hint', ['operador_o', 'si', 'tecla_presionada', 'mover_derecha'], 5, 4, 20, 2),
    pLesson('s3', 46, 'practice', 'Lessons.programming.s3.l46.title', 'Lessons.programming.s3.l46.description', 'Lessons.programming.s3.l46.challenge', 'Lessons.programming.s3.l46.hint', ['operador_y', 'operador_igual', 'operador_mayor', 'si_sino', 'preguntar'], 6, 5, 25, 2),
    pLesson('s3', 47, 'practice', 'Lessons.programming.s3.l47.title', 'Lessons.programming.s3.l47.description', 'Lessons.programming.s3.l47.challenge', 'Lessons.programming.s3.l47.hint', ['aleatorio', 'operador_mayor', 'si_sino', 'decir', 'tocar_sonido'], 5, 4, 20, 2),
    pLesson('s3', 48, 'practice', 'Lessons.programming.s3.l48.title', 'Lessons.programming.s3.l48.description', 'Lessons.programming.s3.l48.challenge', 'Lessons.programming.s3.l48.hint', ['aleatorio', 'si_sino', 'operador_igual', 'preguntar', 'decir'], 7, 5, 30, 2),
    pLesson('s3', 49, 'practice', 'Lessons.programming.s3.l49.title', 'Lessons.programming.s3.l49.description', 'Lessons.programming.s3.l49.challenge', 'Lessons.programming.s3.l49.hint', ['preguntar', 'operador_igual', 'operador_y', 'si_sino', 'decir'], 6, 5, 25, 2),
    pLesson('s3', 50, 'challenge', 'Lessons.programming.s3.l50.title', 'Lessons.programming.s3.l50.description', 'Lessons.programming.s3.l50.challenge', 'Lessons.programming.s3.l50.hint', ['operador_y', 'operador_o', 'operador_mayor', 'si', 'tocando_color', 'decir'], 7, 6, 35, 3),

    // Fase 5: Proyecto Final (51-60)
    pLesson('s3', 51, 'lesson', 'Lessons.programming.s3.l51.title', 'Lessons.programming.s3.l51.description', 'Lessons.programming.s3.l51.challenge', 'Lessons.programming.s3.l51.hint', ['decir'], 4, 2, 10, 1),
    pLesson('s3', 52, 'practice', 'Lessons.programming.s3.l52.title', 'Lessons.programming.s3.l52.description', 'Lessons.programming.s3.l52.challenge', 'Lessons.programming.s3.l52.hint', ['cambiar_fondo'], 4, 3, 15, 1),
    pLesson('s3', 53, 'practice', 'Lessons.programming.s3.l53.title', 'Lessons.programming.s3.l53.description', 'Lessons.programming.s3.l53.challenge', 'Lessons.programming.s3.l53.hint', ['al_presionar_tecla', 'mover_derecha', 'mover_arriba'], 5, 4, 20, 2),
    pLesson('s3', 54, 'practice', 'Lessons.programming.s3.l54.title', 'Lessons.programming.s3.l54.description', 'Lessons.programming.s3.l54.challenge', 'Lessons.programming.s3.l54.hint', ['si', 'tocando_color', 'ir_a', 'por_siempre'], 5, 4, 20, 2),
    pLesson('s3', 55, 'practice', 'Lessons.programming.s3.l55.title', 'Lessons.programming.s3.l55.description', 'Lessons.programming.s3.l55.challenge', 'Lessons.programming.s3.l55.hint', ['si', 'tocando_objeto', 'esconder', 'enviar_mensaje'], 5, 4, 20, 2),
    pLesson('s3', 56, 'practice', 'Lessons.programming.s3.l56.title', 'Lessons.programming.s3.l56.description', 'Lessons.programming.s3.l56.challenge', 'Lessons.programming.s3.l56.hint', ['si_sino', 'al_recibir_mensaje', 'tocando_objeto', 'cambiar_disfraz', 'decir'], 6, 5, 25, 2),
    pLesson('s3', 57, 'practice', 'Lessons.programming.s3.l57.title', 'Lessons.programming.s3.l57.description', 'Lessons.programming.s3.l57.challenge', 'Lessons.programming.s3.l57.hint', ['por_siempre', 'mover_derecha', 'si', 'tocando_borde', 'rebotar'], 5, 4, 20, 2),
    pLesson('s3', 58, 'practice', 'Lessons.programming.s3.l58.title', 'Lessons.programming.s3.l58.description', 'Lessons.programming.s3.l58.challenge', 'Lessons.programming.s3.l58.hint', ['si', 'tocando_objeto', 'enviar_mensaje', 'ir_a', 'por_siempre'], 5, 4, 20, 2),
    pLesson('s3', 59, 'practice', 'Lessons.programming.s3.l59.title', 'Lessons.programming.s3.l59.description', 'Lessons.programming.s3.l59.challenge', 'Lessons.programming.s3.l59.hint', ['si', 'tocando_color', 'enviar_mensaje', 'tocar_sonido', 'decir'], 5, 4, 20, 2),
    pLesson('s3', 60, 'challenge', 'Lessons.programming.s3.l60.title', 'Lessons.programming.s3.l60.description', 'Lessons.programming.s3.l60.challenge', 'Lessons.programming.s3.l60.hint', ['si', 'si_sino', 'tocando_color', 'tocando_objeto', 'al_presionar_tecla', 'por_siempre', 'enviar_mensaje', 'ir_a', 'tocar_sonido'], 8, 8, 50, 5),
];
