// Sample units for Math Grade 4
// These would eventually be stored in a database

import { LearningUnit, createDefaultUnitStructure } from './microLessonSystem';

export const MATH_GRADE_4_UNITS: LearningUnit[] = [
    // --- GRADE 1 ---
    {
        id: 'math_g1_numeration',
        subjectId: 'math',
        gradeLevel: 1,
        order: 1,
        titleEs: 'Números 0-99',
        titleEn: 'Numbers 0-99',
        descriptionEs: 'Contar, ordenar y valor posicional',
        descriptionEn: 'Counting, ordering and place value',
        iconEmoji: '🔢',
        lessons: createDefaultUnitStructure('math_g1_numeration', 'math', 'Numeración', 'Numeration'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g1_operations',
        subjectId: 'math',
        gradeLevel: 1,
        order: 2,
        titleEs: 'Sumas y Restas',
        titleEn: 'Add & Subtract',
        descriptionEs: 'Operaciones básicas sin llevar',
        descriptionEn: 'Basic operations without carrying',
        iconEmoji: '➕',
        lessons: createDefaultUnitStructure('math_g1_operations', 'math', 'Operaciones', 'Operations'),
        prerequisites: ['math_g1_numeration'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g1_geometry',
        subjectId: 'math',
        gradeLevel: 1,
        order: 3,
        titleEs: 'Formas Básicas',
        titleEn: 'Basic Shapes',
        descriptionEs: 'Círculos, cuadrados y triángulos',
        descriptionEn: 'Circles, squares and triangles',
        iconEmoji: '🔺',
        lessons: createDefaultUnitStructure('math_g1_geometry', 'math', 'Geometría', 'Geometry'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g1_measurement',
        subjectId: 'math',
        gradeLevel: 1,
        order: 4,
        titleEs: 'Medidas',
        titleEn: 'Measurement',
        descriptionEs: 'El reloj y las monedas',
        descriptionEn: 'The clock and coins',
        iconEmoji: '📏',
        lessons: createDefaultUnitStructure('math_g1_measurement', 'math', 'Medición', 'Measurement'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },


    // --- GRADE 2 ---
    {
        id: 'math_g2_numeration',
        subjectId: 'math',
        gradeLevel: 2,
        order: 1,
        titleEs: 'Números 0-999',
        titleEn: 'Numbers 0-999',
        descriptionEs: 'Centenas, decenas y unidades',
        descriptionEn: 'Hundreds, tens and ones',
        iconEmoji: '💯',
        lessons: createDefaultUnitStructure('math_g2_numeration', 'math', 'Numeración', 'Numeration'),
        prerequisites: ['math_g1_numeration'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g2_operations',
        subjectId: 'math',
        gradeLevel: 2,
        order: 2,
        titleEs: 'Operaciones',
        titleEn: 'Operations',
        descriptionEs: 'Sumas con llevadas y multiplicaciones',
        descriptionEn: 'Additions with carry and multiplication',
        iconEmoji: '➕',
        lessons: createDefaultUnitStructure('math_g2_operations', 'math', 'Operaciones', 'Operations'),
        prerequisites: ['math_g2_numeration'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g2_geometry',
        subjectId: 'math',
        gradeLevel: 2,
        order: 3,
        titleEs: 'Geometría 3D',
        titleEn: '3D Geometry',
        descriptionEs: 'Formas tridimensionales y simetría',
        descriptionEn: 'Three-dimensional shapes and symmetry',
        iconEmoji: '🧊',
        lessons: createDefaultUnitStructure('math_g2_geometry', 'math', 'Geometría', 'Geometry'),
        prerequisites: ['math_g1_geometry'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g2_measurement',
        subjectId: 'math',
        gradeLevel: 2,
        order: 4,
        titleEs: 'Medidas II',
        titleEn: 'Measurements II',
        descriptionEs: 'Longitud, capacidad y calendario',
        descriptionEn: 'Length, capacity and calendar',
        iconEmoji: '📅',
        lessons: createDefaultUnitStructure('math_g2_measurement', 'math', 'Medición', 'Measurement'),
        prerequisites: ['math_g1_measurement'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g2_fractions',
        subjectId: 'math',
        gradeLevel: 2,
        order: 5,
        titleEs: 'Fracciones Básicas',
        titleEn: 'Basic Fractions',
        descriptionEs: 'Mitad, tercio y cuarto',
        descriptionEn: 'Half, third and quarter',
        iconEmoji: '🍰',
        lessons: createDefaultUnitStructure('math_g2_fractions', 'math', 'Fracciones', 'Fractions'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },

    // --- GRADE 3 ---
    {
        id: 'math_g3_numeration',
        subjectId: 'math',
        gradeLevel: 3,
        order: 1,
        titleEs: 'Números Grandes',
        titleEn: 'Big Numbers',
        descriptionEs: 'Hasta 5 cifras',
        descriptionEn: 'Up to 5 digits',
        iconEmoji: '🔢',
        lessons: createDefaultUnitStructure('math_g3_numeration', 'math', 'Numeración', 'Numeration'),
        prerequisites: ['math_g2_numeration'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g3_operations',
        subjectId: 'math',
        gradeLevel: 3,
        order: 2,
        titleEs: 'Mult. y División',
        titleEn: 'Mult. and Division',
        descriptionEs: 'Algoritmos de multiplicar y dividir',
        descriptionEn: 'Multiplication and division algorithms',
        iconEmoji: '➗',
        lessons: createDefaultUnitStructure('math_g3_operations', 'math', 'Operaciones', 'Operations'),
        prerequisites: ['math_g3_numeration'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g3_fractions',
        subjectId: 'math',
        gradeLevel: 3,
        order: 3,
        titleEs: 'Fracciones y Decimales',
        titleEn: 'Fractions & Decimals',
        descriptionEs: 'Introducción a partes de la unidad',
        descriptionEn: 'Introduction to parts of a whole',
        iconEmoji: '🍰',
        lessons: createDefaultUnitStructure('math_g3_fractions', 'math', 'Fracciones', 'Fractions'),
        prerequisites: ['math_g3_operations'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g3_geometry',
        subjectId: 'math',
        gradeLevel: 3,
        order: 4,
        titleEs: 'Geometría Avanzada',
        titleEn: 'Advanced Geometry',
        descriptionEs: 'Triángulos, círculos y polígonos',
        descriptionEn: 'Triangles, circles and polygons',
        iconEmoji: '📐',
        lessons: createDefaultUnitStructure('math_g3_geometry', 'math', 'Geometría', 'Geometry'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g3_measurement',
        subjectId: 'math',
        gradeLevel: 3,
        order: 5,
        titleEs: 'Problemas Reales',
        titleEn: 'Real Problems',
        descriptionEs: 'Dinero y tiempo en contexto',
        descriptionEn: 'Money and time in context',
        iconEmoji: '💶',
        lessons: createDefaultUnitStructure('math_g3_measurement', 'math', 'Medición', 'Measurement'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g4_multiplication',
        subjectId: 'math',
        gradeLevel: 4,
        order: 1,
        titleEs: 'Multiplicación',
        titleEn: 'Multiplication',
        descriptionEs: 'Multiplica números de varios dígitos',
        descriptionEn: 'Multiply multi-digit numbers',
        iconEmoji: '✖️',
        lessons: createDefaultUnitStructure('math_g4_multiplication', 'math', 'Multiplicación', 'Multiplication'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g4_division',
        subjectId: 'math',
        gradeLevel: 4,
        order: 2,
        titleEs: 'División',
        titleEn: 'Division',
        descriptionEs: 'Divide con y sin resto',
        descriptionEn: 'Divide with and without remainder',
        iconEmoji: '➗',
        lessons: createDefaultUnitStructure('math_g4_division', 'math', 'División', 'Division'),
        prerequisites: ['math_g4_multiplication'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g4_fractions',
        subjectId: 'math',
        gradeLevel: 4,
        order: 3,
        titleEs: 'Fracciones',
        titleEn: 'Fractions',
        descriptionEs: 'Aprende a entender y usar fracciones',
        descriptionEn: 'Learn to understand and use fractions',
        iconEmoji: '🍕',
        lessons: [
            {
                id: 'math_g4_fractions_lesson_0',
                unitId: 'math_g4_fractions',
                order: 0,
                type: 'diagnostic',
                titleEs: 'Diagnóstico: Fracciones',
                titleEn: 'Diagnostic: Fractions',
                descriptionEs: '¿Qué sabes sobre fracciones?',
                descriptionEn: 'What do you know about fractions?',
                durationMinutes: 2,
                exerciseCount: 5,
                xpReward: 10,
                starsReward: 1,
                status: 'available',
            },
            {
                id: 'math_g4_fractions_lesson_1',
                unitId: 'math_g4_fractions',
                order: 1,
                type: 'lesson',
                titleEs: '¿Qué es una fracción?',
                titleEn: 'What is a fraction?',
                descriptionEs: 'Numerador, denominador y representación',
                descriptionEn: 'Numerator, denominator and representation',
                durationMinutes: 5,
                exerciseCount: 8,
                xpReward: 20,
                starsReward: 2,
                status: 'locked',
            },
            {
                id: 'math_g4_fractions_lesson_2',
                unitId: 'math_g4_fractions',
                order: 2,
                type: 'practice',
                titleEs: 'Identificar Fracciones',
                titleEn: 'Identify Fractions',
                descriptionEs: 'Practica con dibujos y números',
                descriptionEn: 'Practice with drawings and numbers',
                durationMinutes: 6,
                exerciseCount: 10,
                xpReward: 25,
                starsReward: 2,
                status: 'locked',
            },
            {
                id: 'math_g4_fractions_lesson_3',
                unitId: 'math_g4_fractions',
                order: 3,
                type: 'lesson',
                titleEs: 'Comparar Fracciones',
                titleEn: 'Compare Fractions',
                descriptionEs: '¿Cuál es mayor o menor?',
                descriptionEn: 'Which is greater or less?',
                durationMinutes: 5,
                exerciseCount: 8,
                xpReward: 20,
                starsReward: 2,
                status: 'locked',
            },
            {
                id: 'math_g4_fractions_lesson_4',
                unitId: 'math_g4_fractions',
                order: 4,
                type: 'practice',
                titleEs: 'Fracciones Equivalentes',
                titleEn: 'Equivalent Fractions',
                descriptionEs: 'Diferentes formas, mismo valor',
                descriptionEn: 'Different forms, same value',
                durationMinutes: 7,
                exerciseCount: 12,
                xpReward: 30,
                starsReward: 3,
                status: 'locked',
            },
            {
                id: 'math_g4_fractions_lesson_5',
                unitId: 'math_g4_fractions',
                order: 5,
                type: 'challenge',
                titleEs: '¡Reto de Fracciones!',
                titleEn: 'Fractions Challenge!',
                descriptionEs: 'Demuestra todo lo aprendido',
                descriptionEn: 'Show everything you learned',
                durationMinutes: 8,
                exerciseCount: 15,
                xpReward: 50,
                starsReward: 5,
                status: 'locked',
            },
        ],
        prerequisites: [],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g4_decimals',
        subjectId: 'math',
        gradeLevel: 4,
        order: 4,
        titleEs: 'Decimales',
        titleEn: 'Decimals',
        descriptionEs: 'Números con punto decimal',
        descriptionEn: 'Numbers with decimal points',
        iconEmoji: '🔢',
        lessons: createDefaultUnitStructure('math_g4_decimals', 'math', 'Decimales', 'Decimals'),
        prerequisites: ['math_g4_fractions'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g4_geometry',
        subjectId: 'math',
        gradeLevel: 4,
        order: 5,
        titleEs: 'Geometría',
        titleEn: 'Geometry',
        descriptionEs: 'Líneas, ángulos y figuras',
        descriptionEn: 'Lines, angles and shapes',
        iconEmoji: '📐',
        lessons: createDefaultUnitStructure('math_g4_geometry', 'math', 'Geometría', 'Geometry'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g4_measurement',
        subjectId: 'math',
        gradeLevel: 4,
        order: 6,
        titleEs: 'Medición',
        titleEn: 'Measurement',
        descriptionEs: 'Unidades y conversiones',
        descriptionEn: 'Units and conversions',
        iconEmoji: '📏',
        lessons: createDefaultUnitStructure('math_g4_measurement', 'math', 'Medición', 'Measurement'),
        prerequisites: ['math_g4_decimals'],
        status: 'available',
        progress: 0,
    },
    // --- GRADE 5 ---
    {
        id: 'math_g5_arithmetic',
        subjectId: 'math',
        gradeLevel: 5,
        order: 1,
        titleEs: 'Operaciones Avanzadas',
        titleEn: 'Advanced Arithmetic',
        descriptionEs: 'Primos, divisibilidad y decimales',
        descriptionEn: 'Primes, divisibility and decimals',
        iconEmoji: '🔢',
        lessons: createDefaultUnitStructure('math_g5_arithmetic', 'math', 'Aritmética', 'Arithmetic'),
        prerequisites: [],
        status: 'available',
        progress: 0,
        slug: 'arithmetic',
        path: '/learning/math/grade5/arithmetic'
    },
    {
        id: 'math_g5_sexagesimal',
        subjectId: 'math',
        gradeLevel: 5,
        order: 2,
        titleEs: 'Sistema Sexagesimal',
        titleEn: 'Sexagesimal System',
        descriptionEs: 'Tiempo y ángulos',
        descriptionEn: 'Time and angles',
        iconEmoji: '⏱️',
        lessons: createDefaultUnitStructure('math_g5_sexagesimal', 'math', 'Sist. Sexagesimal', 'Sexagesimal Sys.'),
        prerequisites: ['math_g5_arithmetic'],
        status: 'available',
        progress: 0,
        slug: 'sexagesimal',
        path: '/learning/math/grade5/sexagesimal'
    },
    {
        id: 'math_g5_geometry',
        subjectId: 'math',
        gradeLevel: 5,
        order: 3,
        titleEs: 'Áreas y Poliedros',
        titleEn: 'Areas & Polyhedra',
        descriptionEs: 'Cálculo de superficies',
        descriptionEn: 'Surface area calculation',
        iconEmoji: '📐',
        lessons: createDefaultUnitStructure('math_g5_geometry', 'math', 'Geometría', 'Geometry'),
        prerequisites: [],
        status: 'available',
        progress: 0,
        slug: 'geometry',
        path: '/learning/math/grade5/geometry'
    },
    {
        id: 'math_g5_fractions',
        subjectId: 'math',
        gradeLevel: 5,
        order: 4,
        titleEs: 'Fracciones',
        titleEn: 'Fractions',
        descriptionEs: 'Equivalencias y comparaciones',
        descriptionEn: 'Equivalence and comparisons',
        iconEmoji: '🍕',
        lessons: createDefaultUnitStructure('math_g5_fractions', 'math', 'Fracciones', 'Fractions'),
        prerequisites: ['math_g5_arithmetic'],
        status: 'available',
        progress: 0,
        slug: 'fractions',
        path: '/learning/math/grade5/fractions'
    },
    // --- GRADE 6 ---
    {
        id: 'math_g6_proportionality',
        subjectId: 'math',
        gradeLevel: 6,
        order: 1,
        titleEs: 'Proporcionalidad',
        titleEn: 'Proportionality',
        descriptionEs: 'Regla de tres y porcentajes',
        descriptionEn: 'Rule of three and percentages',
        iconEmoji: '⚖️',
        lessons: createDefaultUnitStructure('math_g6_proportionality', 'math', 'Proporcionalidad', 'Proportionality'),
        prerequisites: [],
        status: 'available',
        progress: 0,
        slug: 'proportionality',
        path: '/learning/math/grade6/proportionality'
    },
    {
        id: 'math_g6_integers',
        subjectId: 'math',
        gradeLevel: 6,
        order: 2,
        titleEs: 'Números Enteros',
        titleEn: 'Integers',
        descriptionEs: 'Negativos y potencias',
        descriptionEn: 'Negative numbers and powers',
        iconEmoji: '📉',
        lessons: createDefaultUnitStructure('math_g6_integers', 'math', 'Enteros', 'Integers'),
        prerequisites: ['math_g6_proportionality'],
        status: 'available',
        progress: 0,
        slug: 'integers',
        path: '/learning/math/grade6/integers'
    },
    {
        id: 'math_g6_stats',
        subjectId: 'math',
        gradeLevel: 6,
        order: 3,
        titleEs: 'Estadística',
        titleEn: 'Statistics',
        descriptionEs: 'Media, mediana y moda',
        descriptionEn: 'Mean, median and mode',
        iconEmoji: '📊',
        lessons: createDefaultUnitStructure('math_g6_stats', 'math', 'Estadística', 'Statistics'),
        prerequisites: [],
        status: 'available',
        progress: 0,
        slug: 'stats',
        path: '/learning/math/grade6/stats'
    },
    {
        id: 'math_g6_volume',
        subjectId: 'math',
        gradeLevel: 6,
        order: 4,
        titleEs: 'Volumen y 3D',
        titleEn: 'Volume & 3D',
        descriptionEs: 'Cálculo de volumen',
        descriptionEn: 'Volume calculation',
        iconEmoji: '📦',
        lessons: createDefaultUnitStructure('math_g6_volume', 'math', 'Volumen', 'Volume'),
        prerequisites: ['math_g6_integers'],
        status: 'available',
        progress: 0,
        slug: 'volume',
        path: '/learning/math/grade6/volume'
    },
];

// Get unit by ID
export function getUnitById(unitId: string): LearningUnit | undefined {
    return MATH_GRADE_4_UNITS.find(u => u.id === unitId);
}

// Get all units for a grade
export function getUnitsForGrade(gradeLevel: number): LearningUnit[] {
    return MATH_GRADE_4_UNITS.filter(u => u.gradeLevel === gradeLevel);
}
