// Sample units for Math Grade 4
// These would eventually be stored in a database

import { LearningUnit, createDefaultUnitStructure } from './microLessonSystem';

export const MATH_GRADE_4_UNITS: LearningUnit[] = [
    // --- GRADE 1 ---
    {
        id: 'math_g1_numeration',
        subjectId: 'math',
        gradeLevel: 1,
        order: 1,
        titleKey: 'MathGrade1.numeration_title',
        descriptionKey: 'MathGrade1.numeration_description',
        iconEmoji: '🔢',
        lessons: createDefaultUnitStructure('math_g1_numeration', 'math', 'MathGrade1.numeration_title'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g1_operations',
        subjectId: 'math',
        gradeLevel: 1,
        order: 2,
        titleKey: 'MathGrade1.operations_title',
        descriptionKey: 'MathGrade1.operations_description',
        iconEmoji: '➕',
        lessons: createDefaultUnitStructure('math_g1_operations', 'math', 'MathGrade1.operations_title'),
        prerequisites: ['math_g1_numeration'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g1_geometry',
        subjectId: 'math',
        gradeLevel: 1,
        order: 3,
        titleKey: 'MathGrade1.geometry_title',
        descriptionKey: 'MathGrade1.geometry_description',
        iconEmoji: '🔺',
        lessons: createDefaultUnitStructure('math_g1_geometry', 'math', 'MathGrade1.geometry_title'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g1_measurement',
        subjectId: 'math',
        gradeLevel: 1,
        order: 4,
        titleKey: 'MathGrade1.measurement_title',
        descriptionKey: 'MathGrade1.measurement_description',
        iconEmoji: '📏',
        lessons: createDefaultUnitStructure('math_g1_measurement', 'math', 'MathGrade1.measurement_title'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },


    // --- GRADE 2 ---
    {
        id: 'math_g2_numeration',
        subjectId: 'math',
        gradeLevel: 2,
        order: 1,
        titleKey: 'MathGrade2.numeration_title',
        descriptionKey: 'MathGrade2.numeration_description',
        iconEmoji: '💯',
        lessons: createDefaultUnitStructure('math_g2_numeration', 'math', 'MathGrade2.numeration_title'),
        prerequisites: ['math_g1_numeration'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g2_operations',
        subjectId: 'math',
        gradeLevel: 2,
        order: 2,
        titleKey: 'MathGrade2.operations_title',
        descriptionKey: 'MathGrade2.operations_description',
        iconEmoji: '➕',
        lessons: createDefaultUnitStructure('math_g2_operations', 'math', 'MathGrade2.operations_title'),
        prerequisites: ['math_g2_numeration'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g2_geometry',
        subjectId: 'math',
        gradeLevel: 2,
        order: 3,
        titleKey: 'MathGrade2.geometry_title',
        descriptionKey: 'MathGrade2.geometry_description',
        iconEmoji: '🧊',
        lessons: createDefaultUnitStructure('math_g2_geometry', 'math', 'MathGrade2.geometry_title'),
        prerequisites: ['math_g1_geometry'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g2_measurement',
        subjectId: 'math',
        gradeLevel: 2,
        order: 4,
        titleKey: 'MathGrade2.measurement_title',
        descriptionKey: 'MathGrade2.measurement_description',
        iconEmoji: '📅',
        lessons: createDefaultUnitStructure('math_g2_measurement', 'math', 'MathGrade2.measurement_title'),
        prerequisites: ['math_g1_measurement'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g2_fractions',
        subjectId: 'math',
        gradeLevel: 2,
        order: 5,
        titleKey: 'MathGrade2.fractions_title',
        descriptionKey: 'MathGrade2.fractions_description',
        iconEmoji: '🍰',
        lessons: createDefaultUnitStructure('math_g2_fractions', 'math', 'MathGrade2.fractions_title'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },

    // --- GRADE 3 ---
    {
        id: 'math_g3_numeration',
        subjectId: 'math',
        gradeLevel: 3,
        order: 1,
        titleKey: 'MathGrade3.numeration_title',
        descriptionKey: 'MathGrade3.numeration_description',
        iconEmoji: '🔢',
        lessons: createDefaultUnitStructure('math_g3_numeration', 'math', 'MathGrade3.numeration_title'),
        prerequisites: ['math_g2_numeration'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g3_operations',
        subjectId: 'math',
        gradeLevel: 3,
        order: 2,
        titleKey: 'MathGrade3.operations_title',
        descriptionKey: 'MathGrade3.operations_description',
        iconEmoji: '➗',
        lessons: createDefaultUnitStructure('math_g3_operations', 'math', 'MathGrade3.operations_title'),
        prerequisites: ['math_g3_numeration'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g3_fractions',
        subjectId: 'math',
        gradeLevel: 3,
        order: 3,
        titleKey: 'MathGrade3.fractions_title',
        descriptionKey: 'MathGrade3.fractions_description',
        iconEmoji: '🍰',
        lessons: createDefaultUnitStructure('math_g3_fractions', 'math', 'MathGrade3.fractions_title'),
        prerequisites: ['math_g3_operations'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g3_geometry',
        subjectId: 'math',
        gradeLevel: 3,
        order: 4,
        titleKey: 'MathGrade3.geometry_title',
        descriptionKey: 'MathGrade3.geometry_description',
        iconEmoji: '📐',
        lessons: createDefaultUnitStructure('math_g3_geometry', 'math', 'MathGrade3.geometry_title'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g3_measurement',
        subjectId: 'math',
        gradeLevel: 3,
        order: 5,
        titleKey: 'MathGrade3.measurement_title',
        descriptionKey: 'MathGrade3.measurement_description',
        iconEmoji: '💶',
        lessons: createDefaultUnitStructure('math_g3_measurement', 'math', 'MathGrade3.measurement_title'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g4_multiplication',
        subjectId: 'math',
        gradeLevel: 4,
        order: 1,
        titleKey: 'MathGrade4.multiplication_title',
        descriptionKey: 'MathGrade4.multiplication_description',
        iconEmoji: '✖️',
        lessons: createDefaultUnitStructure('math_g4_multiplication', 'math', 'MathGrade4.multiplication_title'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g4_division',
        subjectId: 'math',
        gradeLevel: 4,
        order: 2,
        titleKey: 'MathGrade4.division_title',
        descriptionKey: 'MathGrade4.division_description',
        iconEmoji: '➗',
        lessons: createDefaultUnitStructure('math_g4_division', 'math', 'MathGrade4.division_title'),
        prerequisites: ['math_g4_multiplication'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g4_fractions',
        subjectId: 'math',
        gradeLevel: 4,
        order: 3,
        titleKey: 'MathGrade4.fractions_title',
        descriptionKey: 'MathGrade4.fractions_description',
        iconEmoji: '🍕',
        lessons: [
            {
                id: 'math_g4_fractions_lesson_0',
                unitId: 'math_g4_fractions',
                order: 0,
                type: 'diagnostic',
                titleKey: 'Lessons.math_g4_fractions.l0.title',
                descriptionKey: 'Lessons.math_g4_fractions.l0.description',
                durationMinutes: 2,
                exerciseCount: 5,
                xpReward: 10,
                starsReward: 1,
                status: 'available',
            },
            {
                id: 'math_g4_fractions_lesson_1',
                unitId: 'math_g4_fractions',
                order: 1,
                type: 'lesson',
                titleKey: 'Lessons.math_g4_fractions.l1.title',
                descriptionKey: 'Lessons.math_g4_fractions.l1.description',
                durationMinutes: 5,
                exerciseCount: 8,
                xpReward: 20,
                starsReward: 2,
                status: 'locked',
            },
            {
                id: 'math_g4_fractions_lesson_2',
                unitId: 'math_g4_fractions',
                order: 2,
                type: 'practice',
                titleKey: 'Lessons.math_g4_fractions.l2.title',
                descriptionKey: 'Lessons.math_g4_fractions.l2.description',
                durationMinutes: 6,
                exerciseCount: 10,
                xpReward: 25,
                starsReward: 2,
                status: 'locked',
            },
            {
                id: 'math_g4_fractions_lesson_3',
                unitId: 'math_g4_fractions',
                order: 3,
                type: 'lesson',
                titleKey: 'Lessons.math_g4_fractions.l3.title',
                descriptionKey: 'Lessons.math_g4_fractions.l3.description',
                durationMinutes: 5,
                exerciseCount: 8,
                xpReward: 20,
                starsReward: 2,
                status: 'locked',
            },
            {
                id: 'math_g4_fractions_lesson_4',
                unitId: 'math_g4_fractions',
                order: 4,
                type: 'practice',
                titleKey: 'Lessons.math_g4_fractions.l4.title',
                descriptionKey: 'Lessons.math_g4_fractions.l4.description',
                durationMinutes: 7,
                exerciseCount: 12,
                xpReward: 30,
                starsReward: 3,
                status: 'locked',
            },
            {
                id: 'math_g4_fractions_lesson_5',
                unitId: 'math_g4_fractions',
                order: 5,
                type: 'challenge',
                titleKey: 'Lessons.math_g4_fractions.l5.title',
                descriptionKey: 'Lessons.math_g4_fractions.l5.description',
                durationMinutes: 8,
                exerciseCount: 15,
                xpReward: 50,
                starsReward: 5,
                status: 'locked',
            },
        ],
        prerequisites: [],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g4_decimals',
        subjectId: 'math',
        gradeLevel: 4,
        order: 4,
        titleKey: 'MathGrade4.decimals_title',
        descriptionKey: 'MathGrade4.decimals_description',
        iconEmoji: '🔢',
        lessons: createDefaultUnitStructure('math_g4_decimals', 'math', 'MathGrade4.decimals_title'),
        prerequisites: ['math_g4_fractions'],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g4_geometry',
        subjectId: 'math',
        gradeLevel: 4,
        order: 5,
        titleKey: 'MathGrade4.geometry_title',
        descriptionKey: 'MathGrade4.geometry_description',
        iconEmoji: '📐',
        lessons: createDefaultUnitStructure('math_g4_geometry', 'math', 'MathGrade4.geometry_title'),
        prerequisites: [],
        status: 'available',
        progress: 0,
    },
    {
        id: 'math_g4_measurement',
        subjectId: 'math',
        gradeLevel: 4,
        order: 6,
        titleKey: 'MathGrade4.measurement_title',
        descriptionKey: 'MathGrade4.measurement_description',
        iconEmoji: '📏',
        lessons: createDefaultUnitStructure('math_g4_measurement', 'math', 'MathGrade4.measurement_title'),
        prerequisites: ['math_g4_decimals'],
        status: 'available',
        progress: 0,
    },
    // --- GRADE 5 ---
    {
        id: 'math_g5_arithmetic',
        subjectId: 'math',
        gradeLevel: 5,
        order: 1,
        titleKey: 'MathGrade5.arithmetic_title',
        descriptionKey: 'MathGrade5.arithmetic_description',
        iconEmoji: '🔢',
        lessons: createDefaultUnitStructure('math_g5_arithmetic', 'math', 'MathGrade5.arithmetic_title'),
        prerequisites: [],
        status: 'available',
        progress: 0,
        slug: 'arithmetic',
        path: '/learning/math/grade5/arithmetic'
    },
    {
        id: 'math_g5_sexagesimal',
        subjectId: 'math',
        gradeLevel: 5,
        order: 2,
        titleKey: 'MathGrade5.sexagesimal_title',
        descriptionKey: 'MathGrade5.sexagesimal_description',
        iconEmoji: '⏱️',
        lessons: createDefaultUnitStructure('math_g5_sexagesimal', 'math', 'MathGrade5.sexagesimal_title'),
        prerequisites: ['math_g5_arithmetic'],
        status: 'available',
        progress: 0,
        slug: 'sexagesimal',
        path: '/learning/math/grade5/sexagesimal'
    },
    {
        id: 'math_g5_geometry',
        subjectId: 'math',
        gradeLevel: 5,
        order: 3,
        titleKey: 'MathGrade5.geometry_title',
        descriptionKey: 'MathGrade5.geometry_description',
        iconEmoji: '📐',
        lessons: createDefaultUnitStructure('math_g5_geometry', 'math', 'MathGrade5.geometry_title'),
        prerequisites: [],
        status: 'available',
        progress: 0,
        slug: 'geometry',
        path: '/learning/math/grade5/geometry'
    },
    {
        id: 'math_g5_fractions',
        subjectId: 'math',
        gradeLevel: 5,
        order: 4,
        titleKey: 'MathGrade5.fractions_title',
        descriptionKey: 'MathGrade5.fractions_description',
        iconEmoji: '🍕',
        lessons: createDefaultUnitStructure('math_g5_fractions', 'math', 'MathGrade5.fractions_title'),
        prerequisites: ['math_g5_arithmetic'],
        status: 'available',
        progress: 0,
        slug: 'fractions',
        path: '/learning/math/grade5/fractions'
    },
    // --- GRADE 6 ---
    {
        id: 'math_g6_proportionality',
        subjectId: 'math',
        gradeLevel: 6,
        order: 1,
        titleKey: 'MathGrade6.proportionality_title',
        descriptionKey: 'MathGrade6.proportionality_description',
        iconEmoji: '⚖️',
        lessons: createDefaultUnitStructure('math_g6_proportionality', 'math', 'MathGrade6.proportionality_title'),
        prerequisites: [],
        status: 'available',
        progress: 0,
        slug: 'proportionality',
        path: '/learning/math/grade6/proportionality'
    },
    {
        id: 'math_g6_integers',
        subjectId: 'math',
        gradeLevel: 6,
        order: 2,
        titleKey: 'MathGrade6.integers_title',
        descriptionKey: 'MathGrade6.integers_description',
        iconEmoji: '📉',
        lessons: createDefaultUnitStructure('math_g6_integers', 'math', 'MathGrade6.integers_title'),
        prerequisites: ['math_g6_proportionality'],
        status: 'available',
        progress: 0,
        slug: 'integers',
        path: '/learning/math/grade6/integers'
    },
    {
        id: 'math_g6_stats',
        subjectId: 'math',
        gradeLevel: 6,
        order: 3,
        titleKey: 'MathGrade6.stats_title',
        descriptionKey: 'MathGrade6.stats_description',
        iconEmoji: '📊',
        lessons: createDefaultUnitStructure('math_g6_stats', 'math', 'MathGrade6.stats_title'),
        prerequisites: [],
        status: 'available',
        progress: 0,
        slug: 'stats',
        path: '/learning/math/grade6/stats'
    },
    {
        id: 'math_g6_volume',
        subjectId: 'math',
        gradeLevel: 6,
        order: 4,
        titleKey: 'MathGrade6.volume_title',
        descriptionKey: 'MathGrade6.volume_description',
        iconEmoji: '📦',
        lessons: createDefaultUnitStructure('math_g6_volume', 'math', 'MathGrade6.volume_title'),
        prerequisites: ['math_g6_integers'],
        status: 'available',
        progress: 0,
        slug: 'volume',
        path: '/learning/math/grade6/volume'
    },
];

// Get unit by ID
export function getUnitById(unitId: string): LearningUnit | undefined {
    return MATH_GRADE_4_UNITS.find(u => u.id === unitId);
}

// Get all units for a grade
export function getUnitsForGrade(gradeLevel: number): LearningUnit[] {
    return MATH_GRADE_4_UNITS.filter(u => u.gradeLevel === gradeLevel);
}
